name: CI

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: windows-latest
    name: CI
    steps:
      - uses: actions/checkout@v3

      - name: Check CMake version
        run: cmake --version

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Generate CMake project
        run: cmake -D CMAKE_BUILD_TYPE=RelWithDebInfo -D OPTIMIZE=YES -S. -Bbuild -G Ninja

      - name: Build 64bit release DLL
        run: cmake --build ./build --config RelWithDebInfo --target HorseMenu --

      - name: Check if DLL got built
        run: if (-Not (Test-Path -path "build/HorseMenu.dll")) {throw 1}

      - name: Rename DLL to HorseMenu-dev-{GITHUB_SHA}.dll
        run: |
          del HorseMenu-dev-*.dll
          del HorseMenu-dev-*.pdb
          ren HorseMenu.dll HorseMenu-dev-${{github.sha}}.dll
          ren HorseMenu.pdb HorseMenu.pdb
        working-directory: build/

      - name: Upload Artifact (dll)
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: |
            build/HorseMenu-dev-*.dll
      - name: Upload Artifact (pdb)
        uses: actions/upload-artifact@v3
        with:
          name: pdb
          path: |
            build/HorseMenu.pdb
